name: 'arxiv notification for feishu bot action'
description:
  'Collect arxiv papers everyday and send it to feishu as annoucement'
author: 'junka'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  webhook:
    description: 'feishu bot webhook url'
    required: true
  signkey:
    description: 'set when you enable signature verify'
    required: false
  keyword:
    description: 'fields you care about'
    required: true
    default: 'cvpr'

runs:
  using: node20
  main: dist/index.js
